### ISSUE TITLE
app.jss & co in theme though not selected

### ISSUE THREAD

**Issue by zeromancer1972** [edm00se/generator-xsp#85]
### Expected Behavior
If I do not select to have any resources added (css, js, jss) they shouldn't be referenced in the theme

### Actual Behavior
They ARE referenced and then obviously cause an error when opening the app

### Steps to Reproduce
just walk through the normal yo xsp process and select NOT to have those resources added, look at the produced theme

### Screenshots
n/a

**Comment by edm00se** [comment]
Nuts! Thanks for reporting it Oliver. That should be an easy enough thing to get turned around. I'll also see if I can expand the unit test to check the theme for any erroneous references.
